AllCops:
  TargetRubyVersion: 2.1

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/DotPosition:
  EnforcedStyle: leading

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/HandleExceptions:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantParentheses:
  Enabled: false

TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
